name: Generate Keystore

on:
  workflow_dispatch:  # Jalankan manual sekali saja

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Keystore
        run: |
          keytool -genkeypair \
            -alias pareviestore \
            -keyalg RSA \
            -keysize 2048 \
            -validity 10000 \
            -keystore pareviestore.keystore \
            -storepass parevie123 \
            -keypass parevie123 \
            -dname "CN=Parevie Store, OU=Mobile, O=Parevie, L=Indonesia, S=Indonesia, C=ID"
          
          # Convert ke Base64 agar bisa disimpan sebagai secret
          base64 pareviestore.keystore > keystore_base64.txt
          echo "========================================="
          echo "COPY BASE64 DI BAWAH INI KE SECRET:"
          echo "========================================="
          cat keystore_base64.txt
